print("Cambio el texto del primer print")
print("Prueba 2")
print("Prueba 3 para probar el comando git diff antes de hacer un nuevo commit")
print("Nuevo print para hacer un cambio en main y poder hacer merge con la otra rama")
print("Añado nuevo print en la rama main para crear conflicto a propósito. Soy asín de chungo.")
print("")
print("rama main")
print("")
